# Generated by Django 3.2.5 on 2021-07-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
    ]
