# Generated by Django 3.2.5 on 2021-07-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='question',
            new_name='questions',
        ),
    ]
