# Generated by Django 3.2.5 on 2021-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_question_quizzes_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='right_answer',
            new_name='right_answers',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='answer4',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='answers',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
