# Generated by Django 3.2.5 on 2021-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quizzes_right_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DifferentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer1', models.CharField(max_length=20)),
                ('answer2', models.CharField(max_length=20)),
                ('answer3', models.CharField(max_length=20)),
                ('answer4', models.CharField(max_length=20)),
                ('right_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
